import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'fs'
import { join } from 'path'

const publicRoot = join(process.cwd(), 'public')
const gridSource = readFileSync(join(publicRoot, 'js', 'grid.js'), 'utf8')
const batchSource = readFileSync(join(publicRoot, 'js', 'batch.js'), 'utf8')
const navigationSource = readFileSync(join(publicRoot, 'js', 'navigation.js'), 'utf8')
const appSource = readFileSync(join(publicRoot, 'js', 'app.js'), 'utf8')
const uiSource = readFileSync(join(publicRoot, 'js', 'ui.js'), 'utf8')
const htmlSource = readFileSync(join(publicRoot, 'index.html'), 'utf8')
const layoutSource = readFileSync(join(publicRoot, 'styles', 'layout.css'), 'utf8')
const componentsSource = readFileSync(join(publicRoot, 'styles', 'components.css'), 'utf8')
const lightboxSource = readFileSync(join(publicRoot, 'js', 'lightbox.js'), 'utf8')
const dragdropSource = readFileSync(join(publicRoot, 'js', 'dragdrop.js'), 'utf8')
const materialBrowserSource = readFileSync(join(process.cwd(), 'electron', 'ipc', 'materialBrowser.ts'), 'utf8')
const importIpcSource = readFileSync(join(process.cwd(), 'electron', 'ipc', 'import.ts'), 'utf8')
const screenCaptureSource = readFileSync(join(process.cwd(), 'electron', 'services', 'screenCapture.ts'), 'utf8')
const preloadSource = readFileSync(join(process.cwd(), 'electron', 'preload.ts'), 'utf8')
const screenshotOverlaySource = readFileSync(join(publicRoot, 'screenshot-overlay.html'), 'utf8')
const enhancementsSource = readFileSync(join(publicRoot, 'js', 'enhancements.js'), 'utf8')
const projectIpcSource = readFileSync(join(process.cwd(), 'electron', 'ipc', 'project.ts'), 'utf8')
const projectManagementSource = readFileSync(join(process.cwd(), 'electron', 'services', 'projectManagement.ts'), 'utf8')
const projectsSource = readFileSync(join(publicRoot, 'js', 'projects.js'), 'utf8')
const photoIpcSource = readFileSync(join(process.cwd(), 'electron', 'ipc', 'photo.ts'), 'utf8')

describe('UI/UX refactor guardrails', () => {
  it('keeps paged data loading and virtual grid rendering for large projects', () => {
    expect(appSource).toContain('const PAGE_SIZE = 200')
    expect(appSource).toContain('async function loadMorePhotos')
    expect(gridSource).toContain('function renderVisibleGridItems')
    expect(gridSource).toContain('requestAnimationFrame')
    expect(gridSource).toContain('isVirtualScrollEnabled = true')
  })

  it('keeps outline-only selection and adds select-all for the current result', () => {
    expect(gridSource).not.toContain('selection-indicator')
    expect(gridSource).not.toContain('selection-tray-indicator')
    expect(componentsSource).not.toContain('.selection-indicator')
    expect(componentsSource).toContain('.photo-grid .photo-item.selected')
    expect(gridSource).toContain('function toggleSelectAllPhotos')
    expect(gridSource).toContain('function updateSelectAllButton')
    expect(htmlSource).toContain('id="selectAllBtn"')
    expect(appSource).toContain('toggleSelectAllPhotos')
  })

  it('removes ratings, tags and classification filters from the primary workflow', () => {
    expect(htmlSource).not.toContain('ratingFilter')
    expect(htmlSource).not.toContain('tagFilter')
    expect(htmlSource).not.toContain('评级与标签')
    expect(htmlSource).not.toContain('lightboxRating')
    expect(htmlSource).not.toContain('lightboxTags')
    expect(htmlSource).not.toContain('tagInputModal')
    expect(htmlSource).not.toContain('data-filter="source-web"')
    expect(htmlSource).not.toContain('data-filter="source-local"')
    expect(htmlSource).not.toContain('data-filter="favorite"')
    expect(htmlSource).not.toContain('id="photoCount"')
    expect(htmlSource).not.toContain('js/tags.js')
    expect(existsSync(join(publicRoot, 'js', 'tags.js'))).toBe(false)
    expect(appSource).not.toContain('activeSmartFilters')
    expect(appSource).not.toContain('updateTagFilter')
    expect(appSource).not.toContain('loadCameraLensFilters')
    expect(gridSource).not.toContain('rating-overlay')
    expect(gridSource).not.toContain('tags-overlay')
    expect(batchSource).not.toContain('applyBatchRating')
    expect(batchSource).not.toContain('applyBatchTags')
    expect(lightboxSource).not.toContain('updateLightboxRating')
    expect(lightboxSource).not.toContain('renderLightboxTags')
    expect(photoIpcSource).toContain('(p.filename LIKE ? OR p.filepath LIKE ? OR p.source_url LIKE ? OR p.source_domain LIKE ?)')
    expect(photoIpcSource).not.toContain('t.name LIKE ?))')
  })

  it('places reset and select-all in the right-side header actions', () => {
    const headerActions = htmlSource.match(/<div class="header-tool-actions"[\s\S]*?<\/div>\s*<\/div>\s*<\/header>/)?.[0] || ''
    expect(headerActions).toContain('class="header-selection-actions"')
    expect(headerActions.indexOf('id="clearFilterBtn"')).toBeGreaterThan(-1)
    expect(headerActions.indexOf('id="selectAllBtn"')).toBeGreaterThan(headerActions.indexOf('id="clearFilterBtn"'))
    expect(layoutSource).toContain('.header-selection-actions')
    expect(layoutSource).not.toContain('.filter-bar')
  })

  it('removes the inspiration-board workflow from the renderer', () => {
    expect(htmlSource).not.toContain('灵感板')
    expect(htmlSource).not.toContain('boardModeBtn')
    expect(htmlSource).not.toContain('boardWorkspace')
    expect(htmlSource).not.toContain('selectionTray')
    expect(htmlSource).not.toContain('compareWorkspace')
    expect(navigationSource).not.toContain('openBoardWorkspace')
    expect(enhancementsSource).not.toContain('addSelectedPhotosToBoard')
    expect(layoutSource).not.toContain('selection-tray')
    expect(layoutSource).not.toContain('compare-')
    expect(layoutSource).not.toMatch(/\bboard-/)
    expect(existsSync(join(publicRoot, 'js', 'selectionTray.js'))).toBe(false)
    expect(existsSync(join(publicRoot, 'js', 'compare.js'))).toBe(false)
  })

  it('exports and saves only the current selected photos', () => {
    expect(htmlSource).toContain('id="copyToDesktopBtn"')
    expect(htmlSource).toContain('id="saveDesktopLabel"')
    expect(htmlSource).toContain('id="exportPdfBtn"')
    expect(batchSource).toContain('copySelectedToDesktop')
    expect(batchSource).toContain('Array.from(selectedPhotos)')
    expect(batchSource).toContain('copyToDesktopFolder')
    expect(batchSource).toContain('exportSelectedToPdf')
    expect(batchSource).toContain('exportToPdf')
    expect(batchSource).not.toContain('selectionTrayItems')
    expect(batchSource).not.toContain('exportingBoard')
    expect(htmlSource).not.toContain('deliveryModeBtn')
    expect(htmlSource).not.toContain('shotListWorkspace')
    expect(htmlSource).not.toContain('deliveryWorkspace')
    expect(htmlSource).not.toContain('planningExport.js')
  })

  it('opens material browsing as a project-scoped full workspace and freezes source metadata', () => {
    expect(layoutSource).toContain('width: 100vw')
    expect(layoutSource).not.toContain('width: 520px')
    expect(navigationSource).toContain('ensureCurrentProjectForImport')
    expect(htmlSource).toContain('id="browserProjectContext"')
    expect(materialBrowserSource).toContain('const sourceUrl = item.getURL()')
  })

  it('keeps the material browser embedded on Xiaohongshu and opens Douyin externally', () => {
    expect(htmlSource).toContain('小红书内嵌浏览')
    expect(htmlSource).toContain('id="materialWebview" src="https://www.xiaohongshu.com"')
    expect(htmlSource).toContain('id="openDouyinBtn"')
    expect(htmlSource).not.toContain('browserSourceXhs')
    expect(htmlSource).not.toContain('browserSourceDouyin')
    expect(htmlSource).not.toContain('browserModeToggle')
    expect(htmlSource).not.toContain('takeScreenshot')
    expect(htmlSource).not.toContain('douyinExternalNotice')
    expect(navigationSource).toContain("getElementById('openDouyinBtn')")
    expect(navigationSource).toContain('function ensureEmbeddedWebviewLoaded()')
    expect(navigationSource).toContain('getSavedXiaohongshuUrl()')
    expect(navigationSource).not.toContain("setBrowserSource('douyin')")
    expect(uiSource).toContain("const DOUYIN_URL = 'https://www.douyin.com/'")
    expect(uiSource).toContain('materialBrowser.openExternal(DOUYIN_URL)')
    expect(uiSource).not.toContain("browserSource === 'douyin'")
  })

  it('uses one global Alt+A screenshot flow and copies the result to the clipboard', () => {
    expect(screenCaptureSource).toContain("const HOTKEY = 'Alt+A'")
    expect(screenCaptureSource).not.toContain('Control+Alt+Shift+S')
    expect(screenCaptureSource).toContain('clipboard.writeImage(image)')
    expect(screenCaptureSource).toContain('clipboardCopied')
    expect(screenCaptureSource).toContain("note: 'Pic 截图'")
    expect(preloadSource).toContain('clipboardCopied: boolean')
    expect(preloadSource).not.toContain('saveScreenshot')
    expect(materialBrowserSource).not.toContain('material-browser:save-screenshot')
  })

  it('keeps the screenshot overlay in edit mode until the user confirms', () => {
    expect(screenshotOverlaySource).toContain('id="toolbar"')
    expect(screenshotOverlaySource).toContain('data-tool="arrow"')
    expect(screenshotOverlaySource).toContain('data-tool="mosaic"')
    expect(screenshotOverlaySource).toContain('id="undoButton"')
    expect(screenshotOverlaySource).toContain('id="redoButton"')
    expect(screenshotOverlaySource).toContain('function enterEditing()')
    expect(screenshotOverlaySource).toContain('function completeCapture()')
    expect(screenshotOverlaySource).not.toContain('void saveSelection(point)')
    expect(preloadSource).toContain('capture:copy-to-clipboard')
    expect(screenCaptureSource).toContain("'capture:copy-to-clipboard'")
    expect(screenCaptureSource).toContain("'capture:get-hotkey-status'")
    expect(preloadSource).toContain('getHotkeyStatus')
    expect(htmlSource).toContain('id="screenshotHotkeyStatus"')
  })

  it('keeps keyboard and reduced-motion hooks for the core workflow', () => {
    expect(htmlSource).not.toContain('selectionCompareBtn')
    expect(htmlSource).not.toContain('boardCompareBtn')
    expect(htmlSource).toContain('aria-label="关闭样片详情"')
    const tokens = readFileSync(join(publicRoot, 'styles', 'tokens.css'), 'utf8')
    expect(tokens).toContain(':focus-visible')
    expect(tokens).toContain('prefers-reduced-motion: reduce')
  })

  it('removes the quick-culling workflow and its renderer path', () => {
    expect(htmlSource).not.toContain('快速筛选')
    expect(htmlSource).not.toContain('cullingModeBtn')
    expect(htmlSource).not.toContain('cullingWorkspace')
    expect(htmlSource).not.toContain('workflow-stagebar')
    expect(htmlSource).not.toContain('workflow-stage-note')
    expect(navigationSource).not.toContain('cullingMode')
    expect(appSource).not.toContain('refreshReviewStateCounts')
    expect(layoutSource).not.toContain('culling-workspace')
    expect(existsSync(join(publicRoot, 'js', 'culling.js'))).toBe(false)
  })

  it('supports desktop import and moving library photos between projects', () => {
    expect(htmlSource).toContain('js/dragdrop.js')
    expect(dragdropSource).toContain("application/x-pic-photo-ids")
    expect(dragdropSource).toContain('fromDroppedPaths')
    expect(dragdropSource).toContain('projects.movePhotos')
    expect(gridSource).toContain('item.draggable = true')
    expect(gridSource).toContain('img.draggable = false')
    expect(importIpcSource).toContain("'import:fromDroppedPaths'")
    expect(preloadSource).toContain('getPathForFile')
    expect(projectIpcSource).toContain("'projects:movePhotos'")
    expect(projectManagementSource).toContain('moveProjectSelectionsForPhotos')
  })

  it('keeps lightbox panning and blocks native image dragging', () => {
    expect(htmlSource).toContain('id="lightboxImage" src="" alt="" draggable="false"')
    expect(componentsSource).toContain('-webkit-user-drag: none')
    expect(appSource).toContain("lightboxImage.addEventListener('pointerdown'")
    expect(appSource).not.toContain("lightboxImage.addEventListener('mousedown'")
    expect(lightboxSource).toContain('function applyLightboxTransform')
  })

  it('connects selection actions, project brief editing and browser collection', () => {
    expect(htmlSource).toContain('id="selectionActionBar"')
    expect(htmlSource).toContain('id="projectBriefEditor"')
    expect(htmlSource).toContain('id="briefCoverChoices"')
    expect(htmlSource).toContain('id="briefUseSelectedCoverBtn"')
    expect(htmlSource).toContain('保存简报与封面')
    expect(layoutSource).toContain('-webkit-app-region: no-drag')
    expect(enhancementsSource).toContain('function renderBriefCoverPicker')
    expect(enhancementsSource).toContain("briefEditor?.addEventListener('keydown'")
    expect(htmlSource).toContain('id="browserCollectionDock"')
    expect(htmlSource).not.toContain('boardBatchToolbar')
    expect(htmlSource).toContain('id="globalUndoBtn"')
    expect(enhancementsSource).toContain('function updateSelectionActionBar')
    expect(enhancementsSource).toContain('function recordBrowserCollection')
    expect(enhancementsSource).not.toContain('scheduleBoardMetaSave')
    expect(enhancementsSource).toContain('function pushAppUndo')
    expect(projectIpcSource).toContain("'projects:updateBrief'")
  })

  it('keeps every document id unique after consolidating the header controls', () => {
    const ids = Array.from(htmlSource.matchAll(/\sid="([^"]+)"/g), match => match[1])
    expect(ids.length).toBe(new Set(ids).size)
    expect(htmlSource).toContain('id="headerOverflowMenu"')
    expect(htmlSource).toContain('id="viewToggleLabel"')
  })

  it('provides a keyboard-accessible project context menu for copy and safe delete', () => {
    expect(htmlSource).toContain('id="projectContextMenu"')
    expect(htmlSource).toContain('id="projectDuplicateBtn"')
    expect(htmlSource).toContain('id="projectDeleteBtn"')
    expect(projectsSource).toContain("item.addEventListener('contextmenu'")
    expect(projectsSource).toContain("event.shiftKey && event.key === 'F10'")
    expect(projectsSource).toContain('function duplicateContextProject')
    expect(projectsSource).toContain('function deleteContextProject')
    expect(projectIpcSource).toContain("'projects:duplicate'")
    expect(projectIpcSource).toContain("'projects:delete'")
  })
})
